# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rulebook}
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ryan Lewis"]
  s.date = %q{2011-04-30}
  s.description = %q{Allows you to define a set of 'rules' or dynamic methods to apply to a class.}
  s.email = %q{c00lryguy@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "examples/simple.rb",
    "lib/rulebook.rb",
    "lib/rulebook/class_methods.rb",
    "lib/rulebook/core_ext/module.rb",
    "lib/rulebook/instance_methods.rb",
    "lib/rulebook/rule.rb",
    "rulebook.gemspec",
    "test/helper.rb",
    "test/test_chevy.rb",
    "test/test_rule.rb"
  ]
  s.homepage = %q{http://github.com/c00lryguy/rulebook}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Define methods with regex for dynamic methods.}
  s.test_files = [
    "examples/simple.rb",
    "test/helper.rb",
    "test/test_chevy.rb",
    "test/test_rule.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<meta_tools>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<riot>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_runtime_dependency(%q<meta_tools>, ["> 0.1"])
      s.add_development_dependency(%q<rake>, ["> 0.0.0"])
      s.add_development_dependency(%q<riot>, ["> 0.0.0"])
    else
      s.add_dependency(%q<meta_tools>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<riot>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<meta_tools>, ["> 0.1"])
      s.add_dependency(%q<rake>, ["> 0.0.0"])
      s.add_dependency(%q<riot>, ["> 0.0.0"])
    end
  else
    s.add_dependency(%q<meta_tools>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<riot>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<meta_tools>, ["> 0.1"])
    s.add_dependency(%q<rake>, ["> 0.0.0"])
    s.add_dependency(%q<riot>, ["> 0.0.0"])
  end
end

