# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rulebook}
  s.version = "0.3.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ryan Lewis"]
  s.date = %q{2010-05-01}
  s.description = %q{Lets you define methods with regex for dynamic methods}
  s.email = %q{c00lryguy@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md",
     "TODO"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.md",
     "Rakefile",
     "TODO",
     "VERSION",
     "lib/rulebook.rb",
     "rulebook.gemspec",
     "test/helper.rb",
     "test/test_chevy.rb",
     "test/test_class_methods.rb",
     "test/test_rules.rb",
     "test/test_ryguy.rb",
     "test/test_user.rb"
  ]
  s.homepage = %q{http://github.com/c00lryguy/rulebook}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Allows you to define a set of 'rules' or dynamic methods to apply to a class}
  s.test_files = [
    "test/helper.rb",
     "test/test_chevy.rb",
     "test/test_class_methods.rb",
     "test/test_rules.rb",
     "test/test_ryguy.rb",
     "test/test_user.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

